spring.cloud.stream:
  kafka:
    binder:
      brokers: jsolubuntu:9092
      consumerProperties:
        auto.offset.reset: earliest
    bindings:
      sink-channel:
        consumer:
          autoCommitOffset: false
        configuration:
          auto.offset.reset: earliest
  bindings:
    sink-channel:
      destination: topic-producer-example-source
      group: cg-consumer-examples-basic
